{
 "title": "Container metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "containerName",
    "query": {
     "query": "label_values(container_cpu_usage_nanoseconds_total,container_name)"
    }
   },
   {
    "name": "hostName",
    "query": {
     "query": "label_values(container_cpu_usage_nanoseconds_total,host_name)"
    }
   },
   {
    "name": "disk_operation",
    "query": {
     "query": "label_values(container_blockio_io_service_bytes_recursive_total,operation)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transfered bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_blockio_io_service_bytes_recursive_total{host_name=\"$hostName\",container_name=\"$containerName\", operation=\"$disk_operation\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmitted bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_network_io_usage_tx_bytes_total{host_name=\"$hostName\",container_name=\"$containerName\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transmitted dropped bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_network_io_usage_tx_dropped_total{host_name=\"$hostName\",container_name=\"$containerName\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Received bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_network_io_usage_rx_bytes_total{host_name=\"$hostName\",container_name=\"$containerName\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Received dropped bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_network_io_usage_rx_dropped_total{host_name=\"$hostName\",container_name=\"$containerName\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average CPU usage rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_nanoseconds_total{host_name=\"$hostName\",container_name=\"$containerName\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU utlization ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "container_cpu_utilization_ratio{host_name=\"$hostName\",container_name=\"$containerName\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average memory usage rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_memory_usage_total_bytes{host_name=\"$hostName\",container_name=\"$containerName\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory percent ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "container_memory_percent_ratio{host_name=\"$hostName\",container_name=\"$containerName\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}